server {
    listen 80;
    server_name localhost;

    # Отключаем sendfile, чтобы Nginx не кэшировал файлы в VirtualBox/Docker
    sendfile off;

    # Корень сайта
    root /usr/share/nginx/html;
    index index.php index.html;

    # Основной поиск файлов
    location / {
        try_files $uri $uri/ =404;
    }

    # Настройка для работы с PHP
    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        # Путь внутри контейнера PHP совпадает с твоим volumes
        fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
    }

    # Отключаем кэширование для статики (CSS, JS, картинки)
    location ~* \.(css|js|jpg|jpeg|png|gif|ico|html)$ {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        expires off;
    }
}
