FROM nginx:alpine

# Копируем конфиг внутрь образа
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

# Копируем файлы (на случай, если запустим без volumes)
COPY ./public /usr/share/nginx/html
